name: All CI

on:
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
  windows:
    uses: ./.github/workflows/windows.yml

  all:
    needs: [linux, windows]
    runs-on: ubuntu-latest
    steps:
      - run:
          exit 0
