name: Linux CI

on: [pull_request, push, workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - valami: valami
          - valami: valami
            akarmi: akarmi
    env:
      VALAMI: ${{ matrix.valami && matrix.valami || 'DEFAULT' }}
      AKARMI: ${{ matrix.akarmi && matrix.akarmi || 'DEFAULT' }}
    steps:
      - name: env
        run: |
          echo "AKARMI=$AKARMI"
          echo "VALAMI=$VALAMI"